set_units -time ns

set_false_path -from [get_ports REF]
set_false_path -from [get_ports RESET_N]
set_false_path -from [get_ports DLF_En]
set_false_path -from [get_ports DLF_Clear]
set_false_path -from [get_ports DLF_Ext_Override]
set_false_path -from [get_ports DLF_IN_POL]
set_false_path -from [get_ports DLF_Ext_Data[*]]
set_false_path -from [get_ports DLF_KI[*]]
set_false_path -from [get_ports DLF_KP[*]]
set_false_path -from [get_ports COARSEBINARY_CODE[*]]
set_false_path -from [get_ports MMDCLKDIV_RATIO[*]]
set_false_path -to [get_ports PLLOUT]
set_false_path -to [get_ports PLLOUT_DIV]
set_false_path -to [get_ports CLKDIV_RETIMED]
set_false_path -to [get_ports BBPD_CODE[*]]
set_false_path -to [get_ports DCO_CODE[*]]
set_false_path -to [get_ports DLF_CODE[*]]
